export * from './HomeView/HomeView'
export * from './PaymentView/PaymentView'
export * from './RegisterView/RegisterView'
export * from './LiveVideoView/LiveVideoView'
export * from './LiveVideo2/LiveVideoView2'