export * from './HomeView/HomeView'
export * from './LoginView/LoginView'
export * from './VideoView/VideoView'
export * from './PaymentView/PaymentView'
export * from './DashboardUserView/DashboardUserView'
export * from './RegisterView/RegisterView'