import { RegisterFormWrapper, RegisterInput, RegisterLabel, RadioInputs } from "./RegisterForm.styled"
export const RegisterForm = ()=>{
    return (
        <RegisterFormWrapper>
            <RegisterLabel>Nombre completo:*</RegisterLabel>
            <RegisterInput
                type='text'
                required
            />
            <RegisterLabel>Título profesional:*</RegisterLabel>
            <RadioInputs>
                <div>
                    <RegisterLabel>MÉDICO</RegisterLabel>
                    <RegisterInput
                        type='radio'
                        required
                        name='profession'
                        value='medico'
                    />
                </div>
                <div>
                    <RegisterLabel>PASANTE</RegisterLabel>
                    <RegisterInput
                        type='radio'
                        required
                        name='profession'
                        value='pasante'
                    />
                </div>
                <div>
                    <RegisterLabel>EST. MED</RegisterLabel>
                    <RegisterInput
                        type='radio'
                        required
                        name='profession'
                        value='est-med'
                    />
                </div>
                <div>
                    <RegisterLabel>LIC. ENF</RegisterLabel>
                    <RegisterInput
                        type='radio'
                        required
                        name='profession'
                        value='lic-enf'
                    />
                </div>
                <div>
                    <RegisterLabel>ENF. ESP</RegisterLabel>
                    <RegisterInput
                        type='radio'
                        required
                        name='profession'
                        value='enf-esp'
                    />
                </div>
                <div>
                    <RegisterLabel>EST. ENF</RegisterLabel>
                    <RegisterInput
                        type='radio'
                        required
                        name='profession'
                        value='est-enf'
                    />
                </div>
                <div>
                    <RegisterLabel>QUÍMICO</RegisterLabel>
                    <RegisterInput
                        type='radio'
                        required
                        name='profession'
                        value='quimico'
                    />
                </div>
                <div>
                    <RegisterLabel>BIÓLOGO</RegisterLabel>
                    <RegisterInput
                        type='radio'
                        required
                        name='profession'
                        value='biologo'
                    />
                </div>
                <div>
                    <RegisterLabel>M. EN C</RegisterLabel>
                    <RegisterInput
                        type='radio'
                        required
                        name='profession'
                        value='m-en-c'
                    />
                </div>
                <div>
                    <RegisterLabel>PSICÓLOGO</RegisterLabel>
                    <RegisterInput
                        type='radio'
                        required
                        name='profession'
                        value='psicologo'
                    />
                </div>
                <div>
                    <RegisterLabel>PEDAGOGO</RegisterLabel>
                    <RegisterInput
                        type='radio'
                        required
                        name='profession'
                        value='pedagogo'
                    />
                </div>
                <div>
                    <RegisterLabel>TRABAJADOR SOCIAL</RegisterLabel>
                    <RegisterInput
                        type='radio'
                        required
                        name='profession'
                        value='trabajador-social'
                    />
                </div>
                <div>
                    <RegisterLabel>OTRO</RegisterLabel>
                    <RegisterInput
                        type='text'
                        required
                        name='profession'
                    />
                </div>
            </RadioInputs>
            <RegisterLabel>Institución de procedencia:*</RegisterLabel>
            <RadioInputs>
                <div>
                    <RegisterLabel>IMSS</RegisterLabel>
                    <RegisterInput
                        type='radio'
                        required
                        name='institution'
                        value='IMSS'
                    />
                </div>
                <div>
                    <RegisterLabel>SSA</RegisterLabel>
                    <RegisterInput
                        type='radio'
                        required
                        name='institution'
                        value='SSA'
                    />
                </div>
                <div>
                    <RegisterLabel>ISSTE</RegisterLabel>
                    <RegisterInput
                        type='radio'
                        required
                        name='institution'
                        value='ISSTE'
                    />
                </div>
                <div>
                    <RegisterLabel>GDF</RegisterLabel>
                    <RegisterInput
                        type='radio'
                        required
                        name='institution'
                        value='GDF'
                    />
                </div>
                <div>
                    <RegisterLabel>HIMFG</RegisterLabel>
                    <RegisterInput
                        type='radio'
                        required
                        name='institution'
                        value='HIMFG'
                    />
                </div>
                <div>
                    <RegisterLabel>OTRO</RegisterLabel>
                    <RegisterInput
                        type='radio'
                        required
                        name='institution'
                        value='otro'
                    />
                </div>
            </RadioInputs>
            <RegisterLabel>Cargo:*</RegisterLabel>
            <RegisterInput
                type='text'
                name='cargo'
                required
            />
            <RegisterLabel>Teléfono:*</RegisterLabel>
            <RegisterInput
                type='number'
                name='telefono'
                required
            />
            <RegisterLabel>Edad:*</RegisterLabel>
            <RegisterInput
                type='number'
                name='edad'
                required
            />
            <RegisterLabel>E-mail:*</RegisterLabel>
            <RegisterInput
                type='email'
                name='e-mail'
                required
            />
            <RegisterLabel>¿Es egresado de algún programa del HIMFG?</RegisterLabel>
            <RadioInputs>
                <div>
                    <RegisterLabel>Sí</RegisterLabel>
                    <RegisterInput
                        type='radio'
                        required
                        name='si'
                    />
                </div>
                <div>
                    <RegisterLabel>No</RegisterLabel>
                    <RegisterInput
                        type='radio'
                        required
                        name='no'
                    />
                </div>
            </RadioInputs>
        </RegisterFormWrapper>
    )
}